const Products1 = [
  {
    id: 1,
    name: "[삼삼물산X이태리식탁] 크림 새우 그라탕",
    percent: "",
    price: "7,900원",
    realprice: "",
    image: "../image/goods1.jpeg",
  },
  {
    id: 2,
    name: "[1등급 한우] 안심 스테이크 200g (냉장)",
    percent: "25%",
    price: "29,100원",
    realprice: "38,800원",
    image: "../image/goods2.jpeg",
  },
  {
    id: 3,
    name: "[정호영셰프의 우동카덴] 튀김 우동",
    percent: "12%",
    price: "5,720원",
    realprice: "6,500원",
    image: "../image/goods3.jpeg",
  },
  {
    id: 4,
    name: "[HBAF] 허니버터 아몬드 210g",
    percent: "",
    price: "7,500원",
    realprice: "",
    image: "../image/goods4.jpeg",
  },
  {
    id: 5,
    name: "[교아당] 쫀득한 수제강정 2종 (택1)",
    percent: "",
    price: "8,000원~",
    realprice: "",
    image: "../image/goods5.jpeg",
  },
  {
    id: 6,
    name: "[더오담] 한입 땅콩강정",
    percent: "",
    price: "2,900원",
    realprice: "",
    image: "../image/goods6.jpeg",
  },
  {
    id: 7,
    name: "[아이소이] 수분탱크 마스크 20mlx1매",
    percent: "",
    price: "5,000원",
    realprice: "",
    image: "../image/goods7.jpeg",
  },
  {
    id: 8,
    name: "[느린마을] 소고기 육전",
    percent: "10%",
    price: "7,200원",
    realprice: "8,000원",
    image: "../image/goods8.jpeg",
  },
];
export default Products1;
